import mongoose from "mongoose";
import dotenv from "dotenv";
import Product from "../models/Product";

// Load env
dotenv.config({ path: ".env.local" });

const MONGODB_URI = process.env.MONGODB_URI;

if (!MONGODB_URI) {
  console.error("Missing MONGODB_URI in .env.local");
  process.exit(1);
}

const seedData = [
  // LAPTOPS
  {
    name: "Asus VivoBook 15",
    slug: "asus-vivobook-15",
    sku: "ASUS-V15-01",
    brand: "Asus",
    brandSlug: "asus",
    category: "laptops",
    subcategory: "Student Laptops",
    description: "Compact and lightweight laptop for students and everyday tasks.",
    highlights: ["15.6 inch FHD Display", "Intel Core i3 11th Gen", "8GB RAM", "512GB SSD"],
    inbox: ["Laptop", "Power Adapter", "User Manual"],
    images: ["https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80"],
    price: 35990,
    mrp: 45990,
    stock: 15,
    specs: { processor: "Intel i3", ram: "8GB", storage: "512GB SSD", displaySize: "15.6\"", os: "Windows 11" },
    tags: ["laptop", "asus", "student", "budget"],
    rating: 4.2,
    reviewCount: 45,
    discount: Math.round(((45990 - 35990) / 45990) * 100),
    isFeatured: true
  },
  {
    name: "Dell Inspiron 15",
    slug: "dell-inspiron-15",
    sku: "DELL-I15-02",
    brand: "Dell",
    brandSlug: "dell",
    category: "laptops",
    subcategory: "Business Laptops",
    description: "Reliable business laptop with solid performance.",
    highlights: ["Intel Core i5 12th Gen", "16GB RAM", "512GB SSD", "Backlit Keyboard"],
    inbox: ["Laptop", "Power Adapter"],
    images: ["https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80"],
    price: 54990,
    mrp: 65000,
    stock: 20,
    specs: { processor: "Intel i5", ram: "16GB", storage: "512GB SSD", displaySize: "15.6\"", os: "Windows 11" },
    tags: ["laptop", "dell", "business"],
    rating: 4.5,
    reviewCount: 112,
    discount: Math.round(((65000 - 54990) / 65000) * 100)
  },
  {
    name: "HP Victus 16 Gaming",
    slug: "hp-victus-16",
    sku: "HP-V16-03",
    brand: "HP",
    brandSlug: "hp",
    category: "laptops",
    subcategory: "Gaming Laptops",
    description: "Powerful gaming laptop with advanced cooling.",
    highlights: ["AMD Ryzen 7", "RTX 3060 6GB", "16GB RAM", "1TB SSD", "144Hz Refresh Rate"],
    inbox: ["Laptop", "200W Power Adapter", "Manuals"],
    images: ["https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=80"],
    price: 89990,
    mrp: 105000,
    stock: 5,
    specs: { processor: "AMD Ryzen 7", ram: "16GB", storage: "1TB SSD", displaySize: "16.1\"", gpu: "RTX Series", os: "Windows 11" },
    tags: ["laptop", "gaming", "hp", "rtx"],
    rating: 4.7,
    reviewCount: 88,
    discount: Math.round(((105000 - 89990) / 105000) * 100)
  },
  {
    name: "Lenovo ThinkPad E14",
    slug: "lenovo-thinkpad-e14",
    sku: "LEN-E14-04",
    brand: "Lenovo",
    brandSlug: "lenovo",
    category: "laptops",
    subcategory: "Workstation Laptops",
    description: "Durable and secure laptop for enterprise professionals.",
    highlights: ["Intel Core i7 13th Gen", "16GB RAM", "512GB NVMe SSD", "Fingerprint Reader"],
    inbox: ["Laptop", "65W USB-C Adapter"],
    images: ["https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=80"],
    price: 78990,
    mrp: 95000,
    stock: 8,
    specs: { processor: "Intel i7", ram: "16GB", storage: "512GB SSD", displaySize: "14\"", os: "Windows 11" },
    tags: ["laptop", "lenovo", "thinkpad", "workstation"],
    rating: 4.8,
    reviewCount: 210,
    discount: Math.round(((95000 - 78990) / 95000) * 100)
  },

  // DESKTOPS
  {
    name: "HP ProDesk 400 G7",
    slug: "hp-prodesk-400-g7",
    sku: "HP-PD-01",
    brand: "HP",
    brandSlug: "hp",
    category: "desktops",
    subcategory: "Office Desktops",
    description: "Compact and reliable desktop for office environments.",
    highlights: ["Intel Core i5 10th Gen", "8GB RAM", "256GB SSD + 1TB HDD", "Windows 10 Pro"],
    inbox: ["Desktop PC", "Wired Keyboard", "Wired Mouse", "Power Cable"],
    images: ["https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=800&q=80"],
    price: 45000,
    mrp: 52000,
    stock: 25,
    specs: { processor: "Intel i5", ram: "8GB", formFactor: "SFF" },
    tags: ["desktop", "hp", "office"],
    rating: 4.0,
    reviewCount: 30,
    discount: Math.round(((52000 - 45000) / 52000) * 100)
  },
  {
    name: "Dell OptiPlex 7010",
    slug: "dell-optiplex-7010",
    sku: "DELL-OP-02",
    brand: "Dell",
    brandSlug: "dell",
    category: "desktops",
    subcategory: "Office Desktops",
    description: "Premium commercial desktop with advanced management features.",
    highlights: ["Intel Core i7 13th Gen", "16GB RAM", "512GB PCIe SSD"],
    inbox: ["Desktop PC", "Wireless Keyboard & Mouse Combo"],
    images: ["https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=800&q=80"],
    price: 68000,
    mrp: 80000,
    stock: 12,
    specs: { processor: "Intel i7", ram: "16GB", formFactor: "Tower" },
    tags: ["desktop", "dell", "business"],
    rating: 4.6,
    reviewCount: 75,
    discount: Math.round(((80000 - 68000) / 80000) * 100)
  },
  {
    name: "Zebronics Zeb-Prime H610",
    slug: "zebronics-zeb-prime-h610",
    sku: "ZEB-PR-03",
    brand: "Zebronics",
    brandSlug: "zebronics",
    category: "desktops",
    subcategory: "Pre-built Gaming PCs",
    description: "Entry-level gaming PC built with reliable components.",
    highlights: ["Intel Core i5 12th Gen", "16GB DDR4 RAM", "512GB NVMe", "GTX 1650 4GB", "RGB Cabinet"],
    inbox: ["Gaming Tower", "Power Cable"],
    images: ["https://images.unsplash.com/photo-1587831990711-23ca6441447b?auto=format&fit=crop&w=800&q=80"],
    price: 52000,
    mrp: 65000,
    stock: 10,
    specs: { processor: "Intel i5", ram: "16GB", formFactor: "Tower" },
    tags: ["desktop", "gaming", "zebronics"],
    rating: 4.1,
    reviewCount: 50,
    discount: Math.round(((65000 - 52000) / 65000) * 100)
  },
  {
    name: "Acer Aspire XC",
    slug: "acer-aspire-xc",
    sku: "ACER-XC-04",
    brand: "Acer",
    brandSlug: "acer",
    category: "desktops",
    subcategory: "Mini PCs",
    description: "Space-saving desktop perfect for home use.",
    highlights: ["Intel Core i3 12th Gen", "8GB RAM", "512GB SSD"],
    inbox: ["Mini Desktop", "Power Adapter"],
    images: ["https://images.unsplash.com/photo-1626240217036-71d34c1a7aab?auto=format&fit=crop&w=800&q=80"],
    price: 32000,
    mrp: 38000,
    stock: 18,
    specs: { processor: "Intel i3", ram: "8GB", formFactor: "Mini" },
    tags: ["desktop", "acer", "home", "mini"],
    rating: 4.3,
    reviewCount: 22,
    discount: Math.round(((38000 - 32000) / 38000) * 100)
  },

  // NETWORKING
  {
    name: "TP-Link Archer AX73",
    slug: "tp-link-archer-ax73",
    sku: "TPL-AX73-01",
    brand: "TP-Link",
    brandSlug: "tp-link",
    category: "networking",
    subcategory: "Wi-Fi Routers",
    description: "AX5400 Dual-Band Gigabit Wi-Fi 6 Router.",
    highlights: ["Wi-Fi 6 Speeds up to 5400 Mbps", "6 Antennas", "WPA3 Security", "OneMesh Supported"],
    inbox: ["Wi-Fi Router", "Power Adapter", "RJ45 Ethernet Cable", "Quick Installation Guide"],
    images: ["https://images.unsplash.com/photo-1644361566696-3d442b5b482a?auto=format&fit=crop&w=800&q=80"],
    price: 9499,
    mrp: 12999,
    stock: 40,
    specs: { standard: "WiFi 6", speed: "1Gbps", ports: "4", poe: "No", brand: "TP-Link" },
    tags: ["router", "wifi6", "tp-link", "networking"],
    rating: 4.6,
    reviewCount: 340,
    discount: Math.round(((12999 - 9499) / 12999) * 100)
  },
  {
    name: "Netgear Nighthawk RAX50",
    slug: "netgear-nighthawk-rax50",
    sku: "NTG-RAX50-02",
    brand: "Netgear",
    brandSlug: "netgear",
    category: "networking",
    subcategory: "Wi-Fi Routers",
    description: "High-performance AX5400 Wi-Fi 6 Router for streaming and gaming.",
    highlights: ["Up to 5.4Gbps Speed", "Armor Cybersecurity", "Triple-core 1.5GHz Processor"],
    inbox: ["Router", "Power Adapter", "Ethernet Cable"],
    images: ["https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80"],
    price: 14999,
    mrp: 18999,
    stock: 15,
    specs: { standard: "WiFi 6", speed: "1Gbps", ports: "4", poe: "No", brand: "Netgear" },
    tags: ["router", "netgear", "gaming", "wifi6"],
    rating: 4.7,
    reviewCount: 210,
    discount: Math.round(((18999 - 14999) / 18999) * 100)
  },
  {
    name: "Cisco SG110-16 Switch",
    slug: "cisco-sg110-16",
    sku: "CIS-SG110-03",
    brand: "Cisco",
    brandSlug: "cisco",
    category: "networking",
    subcategory: "Unmanaged Switches",
    description: "16-Port Gigabit Desktop/Rackmount Switch.",
    highlights: ["16 Gigabit Ethernet Ports", "Plug and Play", "Energy Efficient"],
    inbox: ["Switch", "Power Cord", "Mounting Hardware"],
    images: ["https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80"],
    price: 6500,
    mrp: 8500,
    stock: 22,
    specs: { speed: "1Gbps", ports: "16", poe: "No", brand: "Cisco" },
    tags: ["switch", "cisco", "gigabit", "networking"],
    rating: 4.8,
    reviewCount: 95,
    discount: Math.round(((8500 - 6500) / 8500) * 100)
  },
  {
    name: "Ubiquiti UniFi AP AC Lite",
    slug: "ubiquiti-unifi-ap-ac-lite",
    sku: "UBQ-UAP-04",
    brand: "Ubiquiti",
    brandSlug: "ubiquiti",
    category: "networking",
    subcategory: "Access Points",
    description: "Indoor 802.11ac Dual-Radio Access Point.",
    highlights: ["Dual-Band AC1200", "PoE Support", "Sleek Design"],
    inbox: ["Access Point", "Mounting Kit", "Gigabit PoE Adapter"],
    images: ["https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80"],
    price: 7999,
    mrp: 9999,
    stock: 35,
    specs: { standard: "WiFi 5", speed: "1Gbps", ports: "4", poe: "Yes", brand: "Ubiquiti" },
    tags: ["access-point", "ubiquiti", "unifi", "wifi"],
    rating: 4.9,
    reviewCount: 450,
    discount: Math.round(((9999 - 7999) / 9999) * 100)
  },

  // CCTV
  {
    name: "Hikvision DS-2CD2143G2-I",
    slug: "hikvision-4mp-dome",
    sku: "HIK-DOME-01",
    brand: "Hikvision",
    brandSlug: "hikvision",
    category: "cctv",
    subcategory: "IP Cameras",
    description: "4MP AcuSense Fixed Dome Network Camera.",
    highlights: ["4 MP Resolution", "Powered by DarkFighter", "IP67 and IK10", "120 dB WDR"],
    inbox: ["Camera", "Drill Template", "Waterproof Connector", "Screws"],
    images: ["https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80"],
    price: 4500,
    mrp: 6000,
    stock: 50,
    specs: { resolution: "4MP", cameraType: "Dome", weatherproof: "IP67" },
    tags: ["cctv", "hikvision", "dome", "ip-camera"],
    rating: 4.5,
    reviewCount: 120,
    discount: Math.round(((6000 - 4500) / 6000) * 100)
  },
  {
    name: "CP Plus 4MP Bullet",
    slug: "cp-plus-4mp-bullet",
    sku: "CPP-BUL-02",
    brand: "CP Plus",
    brandSlug: "cp-plus",
    category: "cctv",
    subcategory: "Analog Cameras",
    description: "4MP HDCVI IR Bullet Camera with 30m IR range.",
    highlights: ["4 MP Resolution", "Max 30m IR length", "IP67 Weatherproof"],
    inbox: ["Camera", "Mounting Accessories"],
    images: ["https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80"],
    price: 2200,
    mrp: 3500,
    stock: 80,
    specs: { resolution: "4MP", cameraType: "Bullet", weatherproof: "IP67" },
    tags: ["cctv", "cpplus", "bullet", "analog"],
    rating: 4.2,
    reviewCount: 65,
    discount: Math.round(((3500 - 2200) / 3500) * 100)
  },
  {
    name: "Dahua 8-Channel NVR Kit",
    slug: "dahua-8ch-nvr-kit",
    sku: "DAH-NVR-03",
    brand: "Dahua",
    brandSlug: "dahua",
    category: "cctv",
    subcategory: "Complete Kits",
    description: "Complete 8-Channel PoE NVR Kit with 4 2MP Cameras.",
    highlights: ["8-Channel NVR", "4x 2MP Bullet Cameras", "1TB HDD Included", "Plug and Play"],
    inbox: ["8CH NVR", "4 Cameras", "1TB HDD", "Ethernet Cables", "Mouse"],
    images: ["https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80"],
    price: 18500,
    mrp: 24000,
    stock: 10,
    specs: { resolution: "2MP", cameraType: "Bullet", channels: "8" },
    tags: ["cctv", "dahua", "nvr", "kit"],
    rating: 4.4,
    reviewCount: 42,
    discount: Math.round(((24000 - 18500) / 24000) * 100)
  },
  {
    name: "Godrej SeeThru 4K Bullet",
    slug: "godrej-seethru-4k-bullet",
    sku: "GOD-BUL-04",
    brand: "Godrej",
    brandSlug: "godrej",
    category: "cctv",
    subcategory: "IP Cameras",
    description: "Ultra HD 4K IP Bullet Camera for premium surveillance.",
    highlights: ["8MP 4K Resolution", "Color Night Vision", "Two-way Audio", "IP67"],
    inbox: ["Camera", "Adapter", "Mounting Template"],
    images: ["https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80"],
    price: 8500,
    mrp: 12000,
    stock: 25,
    specs: { resolution: "4K", cameraType: "Bullet", weatherproof: "IP67" },
    tags: ["cctv", "godrej", "4k", "bullet"],
    rating: 4.7,
    reviewCount: 38,
    discount: Math.round(((12000 - 8500) / 12000) * 100)
  },

  // ACCESSORIES
  {
    name: "LG 27\" 4K Monitor",
    slug: "lg-27-4k-monitor",
    sku: "LG-MON-01",
    brand: "LG",
    brandSlug: "lg",
    category: "accessories",
    subcategory: "Monitors",
    description: "27 inch 4K UHD IPS Display with VESA DisplayHDR 400.",
    highlights: ["27\" 4K UHD (3840 x 2160)", "sRGB 98% Color Gamut", "AMD FreeSync"],
    inbox: ["Monitor", "Stand", "Power Cord", "HDMI Cable"],
    images: ["https://images.unsplash.com/photo-1527443154391-507e9dc6c5cc?auto=format&fit=crop&w=800&q=80"],
    price: 28999,
    mrp: 35000,
    stock: 15,
    specs: { compatibility: "Universal" },
    tags: ["monitor", "lg", "4k", "display"],
    rating: 4.8,
    reviewCount: 250,
    discount: Math.round(((35000 - 28999) / 35000) * 100)
  },
  {
    name: "Logitech MX Keys",
    slug: "logitech-mx-keys",
    sku: "LOG-MX-02",
    brand: "Logitech",
    brandSlug: "logitech",
    category: "accessories",
    subcategory: "Keyboards & Mice",
    description: "Advanced Wireless Illuminated Keyboard.",
    highlights: ["Perfect Stroke Keys", "Multi-Device Flow", "USB-C Rechargeable"],
    inbox: ["Keyboard", "Unifying Receiver", "USB-C Cable"],
    images: ["https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=800&q=80"],
    price: 9999,
    mrp: 12999,
    stock: 45,
    specs: { compatibility: "Universal" },
    tags: ["keyboard", "logitech", "wireless", "premium"],
    rating: 4.9,
    reviewCount: 890,
    discount: Math.round(((12999 - 9999) / 12999) * 100)
  },
  {
    name: "APC 600VA UPS",
    slug: "apc-600va-ups",
    sku: "APC-UPS-03",
    brand: "APC",
    brandSlug: "apc",
    category: "accessories",
    subcategory: "UPS & Power",
    description: "Battery Backup & Surge Protector for Electronics and Computers.",
    highlights: ["600VA / 360W Capacity", "3 Battery Backup Outlets", "Surge Protection"],
    inbox: ["UPS", "User Manual"],
    images: ["https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80"],
    price: 2800,
    mrp: 3500,
    stock: 100,
    specs: { compatibility: "Universal" },
    tags: ["ups", "apc", "power", "backup"],
    rating: 4.5,
    reviewCount: 540,
    discount: Math.round(((3500 - 2800) / 3500) * 100)
  },
  {
    name: "Seagate 2TB External HDD",
    slug: "seagate-2tb-external-hdd",
    sku: "SEA-HDD-04",
    brand: "Seagate",
    brandSlug: "seagate",
    category: "accessories",
    subcategory: "External Storage",
    description: "Portable External Hard Drive USB 3.0 for PC and Mac.",
    highlights: ["2TB Capacity", "USB 3.0 interface", "Drag and Drop file saving"],
    inbox: ["External HDD", "USB 3.0 Cable"],
    images: ["https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&w=800&q=80"],
    price: 5500,
    mrp: 7500,
    stock: 60,
    specs: { compatibility: "Universal" },
    tags: ["hdd", "seagate", "storage", "external"],
    rating: 4.6,
    reviewCount: 1200,
    discount: Math.round(((7500 - 5500) / 7500) * 100)
  }
];

async function seedDatabase() {
  try {
    console.log("Connecting to MongoDB...");
    await mongoose.connect(MONGODB_URI as string);
    console.log("Connected. Clearing old products...");
    
    await Product.deleteMany({});
    console.log("Old products deleted.");

    console.log("Inserting new seed data...");
    await Product.insertMany(seedData);
    
    console.log("✅ Seed completed successfully!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Seed failed:", error);
    process.exit(1);
  }
}

seedDatabase();
